apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: otp-email-bot
  namespace: otp-email-bot
  labels:
    app: otp-email-bot
spec:
  serviceName: otp-email-bot
  replicas: 1
  selector:
    matchLabels:
      app: otp-email-bot
  template:
    metadata:
      labels:
        app: otp-email-bot
    spec:
      containers:
        - name: otp-email-bot
          image: ideavn/otp-email-bot:{latest}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: otp-email-bot-env
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi